export const ROUTES = {
    LOGIN: '/',
    HOME: '/home',
    ENCUESTAS: '/encuestas',
    ENCUESTAS_CREAR: '/encuestas/crear',
    ENCUESTAS_GESTIONAR: (id: string) => `/encuestas/${id}/gestionar`,
    ENCUESTAS_ANALYTICS: (id: string) => `/encuestas/${id}/analytics`,
    ENCUESTAS_RESPONDER: (uuid: string) => `/encuestas/responder/${uuid}`,
    ENCUESTAS_RESPONDER_SHORT: (uuid: string) => `/survey/${uuid}`,
    FORMULARIOS: '/formularios',
    FORMULARIOS_CREAR: '/formularios/crear',
    ORGULLO_UP: '/orgullo-up',
    ACERCA_DE: '/acerca-de',
    CURSOS: '/cursos',
    ACTUALIZAR_EGRESADO: '/actualizar-egresado',
    GRUPOS: '/grupos',
    GRUPOS_CREAR: '/grupos/crear',
    GRUPOS_EDITAR: (id: string) => `/grupos/editar/${id}`,
    EVENTOS_AUTOMATICOS: '/eventos-automaticos',
    EVENTOS_AUTOMATICOS_CREAR: '/eventos-automaticos/crear',
    EVENTOS_AUTOMATICOS_EDITAR: (id: string | number) => `/eventos-automaticos/editar/${id}`,
    EVENTOS_AUTOMATICOS_HISTORIAL: (id: string | number) => `/eventos-automaticos/historial/${id}`
} as const;